<?php $this->extend('layouts/admin'); use App\Helpers\Form; ?>
<div class="page-head"><div><h1>Price levels</h1><p>Assign users to a level to give them a discount on every service. A user's custom discount overrides a smaller level discount.</p></div><button class="btn btn-primary" type="button" data-open-dialog="lvl-dialog" data-reset><?= icon('plus') ?> Add level</button></div>
<div class="card"><div class="table-wrap"><table class="table table-cards"><thead><tr><th>Name</th><th class="num">Discount</th><th class="num">Users</th><th></th></tr></thead><tbody>
<?php foreach ($levels as $l): ?><tr><td class="cell-main cell-title"><?= e($l['name']) ?></td><td data-label="Discount" class="num"><?= e($l['discount_percent']) ?>%</td><td data-label="Users" class="num"><?= (int) $l['users'] ?></td>
  <td class="actions"><button class="btn btn-ghost btn-sm" type="button" data-open-dialog="lvl-dialog" data-fill="<?= json_attr(['id' => $l['id'], 'name' => $l['name'], 'discount_percent' => $l['discount_percent']]) ?>"><?= icon('edit') ?></button><form class="inline-form" method="post" action="<?= e(admin_url('price-levels/' . $l['id'] . '/delete')) ?>" data-confirm="Delete level? Users on it return to standard pricing."><?= csrf_field() ?><button class="btn btn-ghost btn-sm" type="submit"><?= icon('trash') ?></button></form></td></tr><?php endforeach ?>
</tbody></table></div></div>
<dialog class="modal" id="lvl-dialog"><div class="modal-head"><h3>Price level</h3><button class="btn btn-ghost btn-icon btn-sm" type="button" data-close-dialog><?= icon('x') ?></button></div><div class="modal-body">
  <form method="post" action="<?= e(admin_url('price-levels/save')) ?>"><?= csrf_field() ?><input type="hidden" name="id" value=""><?= Form::input('name', 'Name', '', ['required' => true]) ?><?= Form::input('discount_percent', 'Discount %', '0', ['type' => 'number', 'step' => '0.01', 'min' => 0, 'max' => 100]) ?><button class="btn btn-primary btn-block" type="submit">Save</button></form>
</div></dialog>
