<?php $this->extend('layouts/admin'); ?>
<div class="page-head"><div><h1>Affiliates</h1><p>Commission: <?= e(setting('referral_percent')) ?>% of deposits · minimum transfer <?= e(money(setting('referral_min_withdrawal'))) ?> · <?= setting('referral_enabled', '1') === '1' ? 'enabled' : 'disabled' ?>. <a href="<?= e(admin_url('settings?tab=referral')) ?>">Change</a></p></div></div>
<div class="stats" style="grid-template-columns:repeat(2,minmax(0,1fr))"><div class="stat"><div><div class="stat-label">Commissions paid</div><div class="stat-value"><?= e(money($totals['paid'])) ?></div></div></div><div class="stat"><div><div class="stat-label">Commission events</div><div class="stat-value"><?= number_format((int) $totals['n']) ?></div></div></div></div>
<div class="grid-2">
  <div class="card"><div class="card-header"><h2>Top affiliates</h2></div><div class="table-wrap"><table class="table table-cards"><thead><tr><th>User</th><th class="num">Referrals</th><th class="num">Earned</th><th class="num">Unpaid</th></tr></thead><tbody>
    <?php foreach ($top as $t): ?><tr><td class="cell-main"><a href="<?= e(admin_url('users/' . $t['id'])) ?>"><?= e($t['username']) ?></a></td><td data-label="Referrals" class="num"><?= (int) $t['referrals'] ?></td><td data-label="Earned" class="num"><?= e(money($t['earned'])) ?></td><td data-label="Unpaid" class="num"><?= e(money($t['referral_balance'])) ?></td></tr><?php endforeach ?>
    <?php if (!$top): ?><tr><td colspan="4" class="text-center text-muted">No affiliates yet.</td></tr><?php endif ?></tbody></table></div></div>
  <div class="card"><div class="card-header"><h2>Referral links</h2></div><div class="table-wrap"><table class="table table-cards"><thead><tr><th>Referrer</th><th>Referred</th><th>IP</th><th>Status</th><th></th></tr></thead><tbody>
    <?php foreach ($refs->items as $r): ?><tr><td data-label="Referrer"><?= e($r['referrer']) ?></td><td class="cell-main"><?= e($r['referred']) ?><div class="cell-sub"><?= e(fmt_date($r['created_at'], 'M j, Y')) ?></div></td><td data-label="IP" class="mono text-xs"><?= e($r['ip']) ?></td><td data-label="Status"><?= $r['status'] === 'active' ? status_badge('active') : '<span class="badge badge-danger">Blocked</span>' ?></td>
      <td class="actions"><form method="post" action="<?= e(admin_url('affiliates/' . $r['id'] . '/block')) ?>"><?= csrf_field() ?><button class="btn btn-ghost btn-sm" type="submit"><?= $r['status'] === 'active' ? 'Block' : 'Unblock' ?></button></form></td></tr><?php endforeach ?>
    <?php if (!$refs->items): ?><tr><td colspan="5" class="text-center text-muted">No referrals yet.</td></tr><?php endif ?></tbody></table></div><?= $refs->links(\App\Core\App::request()) ?></div>
</div>
