<?php

declare(strict_types=1);

namespace App\Core;

/**
 * Minimal .env reader (KEY=VALUE, # comments, optional quotes).
 * Values are kept in a private store rather than putenv() so they do not leak
 * into child processes or phpinfo().
 */
final class Env
{
    private static array $values = [];

    public static function load(string $file): void
    {
        if (!is_file($file) || !is_readable($file)) {
            return;
        }
        foreach (file($file, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) ?: [] as $line) {
            $line = trim($line);
            if ($line === '' || $line[0] === '#' || !str_contains($line, '=')) {
                continue;
            }
            [$key, $value] = explode('=', $line, 2);
            $key = trim($key);
            $value = trim($value);
            if ($value !== '' && ($value[0] === '"' || $value[0] === "'") && str_ends_with($value, $value[0])) {
                $quote = $value[0];
                $value = substr($value, 1, -1);
                if ($quote === '"') {
                    $value = str_replace(['\\n', '\\"', '\\\\'], ["\n", '"', '\\'], $value);
                }
            } elseif (($hash = strpos($value, ' #')) !== false) {
                $value = rtrim(substr($value, 0, $hash));
            }
            self::$values[$key] = $value;
        }
    }

    public static function get(string $key, mixed $default = null): mixed
    {
        if (array_key_exists($key, self::$values)) {
            $v = self::$values[$key];
        } elseif (($server = getenv($key)) !== false) {
            $v = $server;
        } else {
            return $default;
        }
        return match (strtolower((string) $v)) {
            'true', '(true)' => true,
            'false', '(false)' => false,
            'null', '(null)' => null,
            default => $v,
        };
    }

    public static function set(string $key, string $value): void
    {
        self::$values[$key] = $value;
    }

    /** Render an .env file body from key/value pairs (used by the installer). */
    public static function render(array $pairs): string
    {
        $out = "# Generated by the installer on " . gmdate('Y-m-d H:i:s') . " UTC\n";
        $out .= "# Keep this file private. It is blocked from web access by .htaccess.\n\n";
        foreach ($pairs as $key => $value) {
            if ($value === null) {
                $out .= "\n";
                continue;
            }
            $value = (string) $value;
            if ($value === '' || preg_match('/^[A-Za-z0-9_\-.:\/@+]*$/', $value)) {
                $out .= "{$key}={$value}\n";
            } else {
                $out .= $key . '="' . str_replace(['\\', '"', "\n"], ['\\\\', '\\"', '\\n'], $value) . "\"\n";
            }
        }
        return $out;
    }
}
